defaults:
  - model@tsgrasp_model: minkowski_graspnet
  - model@ctn_model: temporal_ctn
  - training: default
  - data: acronymvid
  - _self_

ctn_ckpt: /home/tim/Research/tsgrasp/ctn_model.ckpt
# tsgrasp_ckpt: /home/tim/Research/tsgrasp/tsgrasp_model.ckpt
tsgrasp_ckpt: /home/tim/Research/tsgrasp/ckpts/45000_1/model.ckpt

training:
  gpus: 0
  batch_size: 1

data:
  data_cfg:
    points_per_frame: 45000