# @package training
gpus: 1
batch_size: 8
max_epochs: 100
optimizer:
  learning_rate: 0.00025
  lr_decay: 0.99
# resume_from_checkpoint: "/home/tim/Research/tsgrasp/outputs/2021-09-17/11-32-05/default/0/checkpoints/epoch=1-step=31.ckpt"

save_animations: False

use_wandb: False
wandb:
  project: "TSGrasp"
  experiment: "test"
  notes: